/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AuthRouteRouteImport } from "./routes/_auth/route"
import { Route as AuthMainAlbumsRouteImport } from "./routes/_auth/_main/albums"
import { Route as AuthMainArtistsRouteImport } from "./routes/_auth/_main/artists"
import { Route as AuthMainLabelsRouteImport } from "./routes/_auth/_main/labels"
import { Route as AuthMainMixesRouteImport } from "./routes/_auth/_main/mixes"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMainAlbumsRoute = AuthMainAlbumsRouteImport.update({
  id: "/_main/albums",
  path: "/albums",
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMainArtistsRoute = AuthMainArtistsRouteImport.update({
  id: "/_main/artists",
  path: "/artists",
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMainLabelsRoute = AuthMainLabelsRouteImport.update({
  id: "/_main/labels",
  path: "/labels",
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMainMixesRoute = AuthMainMixesRouteImport.update({
  id: "/_main/mixes",
  path: "/mixes",
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/albums": typeof AuthMainAlbumsRoute
  "/artists": typeof AuthMainArtistsRoute
  "/labels": typeof AuthMainLabelsRoute
  "/mixes": typeof AuthMainMixesRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/albums": typeof AuthMainAlbumsRoute
  "/artists": typeof AuthMainArtistsRoute
  "/labels": typeof AuthMainLabelsRoute
  "/mixes": typeof AuthMainMixesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_auth": typeof AuthRouteRouteWithChildren
  "/_auth/_main/albums": typeof AuthMainAlbumsRoute
  "/_auth/_main/artists": typeof AuthMainArtistsRoute
  "/_auth/_main/labels": typeof AuthMainLabelsRoute
  "/_auth/_main/mixes": typeof AuthMainMixesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/albums" | "/artists" | "/labels" | "/mixes"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/albums" | "/artists" | "/labels" | "/mixes"
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/_auth/_main/albums"
    | "/_auth/_main/artists"
    | "/_auth/_main/labels"
    | "/_auth/_main/mixes"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth/_main/albums": {
      id: "/_auth/_main/albums"
      path: "/albums"
      fullPath: "/albums"
      preLoaderRoute: typeof AuthMainAlbumsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/_auth/_main/artists": {
      id: "/_auth/_main/artists"
      path: "/artists"
      fullPath: "/artists"
      preLoaderRoute: typeof AuthMainArtistsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/_auth/_main/labels": {
      id: "/_auth/_main/labels"
      path: "/labels"
      fullPath: "/labels"
      preLoaderRoute: typeof AuthMainLabelsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    "/_auth/_main/mixes": {
      id: "/_auth/_main/mixes"
      path: "/mixes"
      fullPath: "/mixes"
      preLoaderRoute: typeof AuthMainMixesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthMainAlbumsRoute: typeof AuthMainAlbumsRoute
  AuthMainArtistsRoute: typeof AuthMainArtistsRoute
  AuthMainLabelsRoute: typeof AuthMainLabelsRoute
  AuthMainMixesRoute: typeof AuthMainMixesRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthMainAlbumsRoute: AuthMainAlbumsRoute,
  AuthMainArtistsRoute: AuthMainArtistsRoute,
  AuthMainLabelsRoute: AuthMainLabelsRoute,
  AuthMainMixesRoute: AuthMainMixesRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
